language: go

sudo: false
  
before_install:
  - go get github.com/mattn/goveralls

before_script:
  - go vet ./...

go:
  - 1.7
  - 1.8
  - tip

env:
  XRIBBLE_KEY=some-thirty-two-byte-array

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
